## This sql script is similar to the one in "learn_db.sql"
## However, this one is generated by IntelliJ


create table if not exists learn_test.branch
(
    id             int          not null
        primary key,
    mgr_id         int          null,
    mgr_start_date date         null,
    branch_name    varchar(255) null,
    constraint UK_8vnjj1wbmfqnh6gnf6dmrmj9b
        unique (mgr_id)
);

create table if not exists learn_test.branch_seq
(
    next_val bigint null
);

create table if not exists learn_test.branch_supplier
(
    branch_id     int          not null,
    supplier_name varchar(255) not null,
    supply_type   varchar(255) null,
    primary key (branch_id, supplier_name),
    constraint FKtham4pmyhfqwgmjl1t0a87nf5
        foreign key (branch_id) references learn_test.branch (id)
);

create table if not exists learn_test.client
(
    branch_id   int          null,
    id          int          not null
        primary key,
    client_name varchar(255) null,
    constraint FKjuq9plij8n9k8wvbbnus30xk4
        foreign key (branch_id) references learn_test.branch (id)
);

create table if not exists learn_test.employee
(
    birth_day  date            null,
    branch_id  int             null,
    id         int auto_increment
        primary key,
    super_id   int             null,
    salary     bigint          null,
    first_name varchar(255)    not null,
    last_name  varchar(255)    null,
    sex        enum ('F', 'M') null,
    constraint FKcvhlsx8tao1rxt7mpxrot61jt
        foreign key (branch_id) references learn_test.branch (id),
    constraint FKml6sugostm56dn5egj5mjgec2
        foreign key (super_id) references learn_test.employee (id)
);

alter table learn_test.branch
    add constraint FKm4v5q1nm41liuubj2cfxhxf50
        foreign key (mgr_id) references learn_test.employee (id);

create table if not exists learn_test.employee_seq
(
    next_val bigint null
);

create table if not exists learn_test.todo_entity
(
    done bit          null,
    id   bigint auto_increment
        primary key,
    task varchar(255) null
);

create table if not exists learn_test.works_with
(
    client_id   int          not null,
    emp_id      int          not null,
    total_sales varchar(255) null,
    primary key (client_id, emp_id),
    constraint FKjutrc2kbjyet3i1ky6d8vlc7k
        foreign key (client_id) references learn_test.client (id),
    constraint FKmqmfnfqur8ij2ji0uftr2889g
        foreign key (emp_id) references learn_test.employee (id)
);

